-- LUỒNG 3: NHÂN SỰ & PHÂN QUYỀN (Tạo trước vì không phụ thuộc bảng khác)
CREATE TABLE VAI_TRO (
    MAVAITRO SERIAL PRIMARY KEY,
    TENVAITRO VARCHAR(100) NOT NULL,
    QUYENHAN JSONB NOT NULL
);

CREATE TABLE NHANVIEN (
    MANHANVIEN SERIAL PRIMARY KEY,
    HOTEN VARCHAR(255) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL
);

CREATE TABLE TAI_KHOAN_NHAN_VIEN (
    MANHANVIEN INTEGER PRIMARY KEY REFERENCES NHANVIEN(MANHANVIEN),
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORDHASH VARCHAR(255) NOT NULL,
    NGAYTAO DATE NOT NULL DEFAULT CURRENT_DATE,
    TRANG_THAI BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE PHAN_QUYEN_NHAN_VIEN (
    MAVAITRO INTEGER REFERENCES VAI_TRO(MAVAITRO),
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    PRIMARY KEY (MAVAITRO, MANHANVIEN)
);

-- LUỒNG 2: KHÁCH HÀNG & THÚ CƯNG
CREATE TABLE DOI_TAC (
    MADOITAC SERIAL PRIMARY KEY,
    TENDOITAC VARCHAR(255) NOT NULL,
    SODIENTHOAI VARCHAR(20),
    DIACHI VARCHAR(255),
    LOAIDOITAC VARCHAR(50) -- KHACH_HANG, NHA_CUNG_CAP
);

CREATE TABLE KHACH_HANG (
    MADOITAC INTEGER PRIMARY KEY REFERENCES DOI_TAC(MADOITAC),
    DIEMTICHLUY INTEGER NOT NULL DEFAULT 0,
    LOAIKHACHHANG VARCHAR(50) NOT NULL DEFAULT 'Đồng'
);

CREATE TABLE HO_SO_THU_CUNG (
    MATHUCUNG SERIAL PRIMARY KEY,
    MADOITAC INTEGER REFERENCES KHACH_HANG(MADOITAC),
    TENTHUCUNG VARCHAR(100) NOT NULL,
    LOAITHUCUNG VARCHAR(50),
    GIOITINH BOOLEAN
);

-- LUỒNG 1: SẢN PHẨM & KHO
CREATE TABLE SAN_PHAM (
    MASANPHAM SERIAL PRIMARY KEY,
    TENSANPHAM VARCHAR(255) NOT NULL,
    LOAISANPHAM VARCHAR(50) NOT NULL, -- Hàng hóa / Dịch vụ
    DONVITINH VARCHAR(20),
    GIANIEMYET BIGINT,
    COTHEMUA BOOLEAN,
    COTHEBAN BOOLEAN,
    HINHANH TEXT
);

CREATE TABLE PHIEU_KHO (
    SOPHIEU VARCHAR(50) PRIMARY KEY,
    LOAIPHIEU VARCHAR(20) NOT NULL, -- Nhập / Xuất
    NGAYLAP DATE NOT NULL DEFAULT CURRENT_DATE,
    NGUOIPHUTRACH INTEGER REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CHI_TIET_PHIEU (
    MACHITIET SERIAL PRIMARY KEY,
    SOPHIEU VARCHAR(50) REFERENCES PHIEU_KHO(SOPHIEU),
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    SOLUONG INTEGER NOT NULL,
    DONGIA BIGINT NOT NULL
);

CREATE TABLE TON_KHO (
    MASANPHAM INTEGER PRIMARY KEY REFERENCES SAN_PHAM(MASANPHAM),
    SOLUONGTON INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE KIEM_KE (
    MAKIEMKE SERIAL PRIMARY KEY,
    NGAYKIEMKE DATE NOT NULL DEFAULT CURRENT_DATE,
    NGUOIKIEMKE INTEGER REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CHI_TIET_KIEM_KE (
    MACHITIET SERIAL PRIMARY KEY,
    MAKIEMKE INTEGER REFERENCES KIEM_KE(MAKIEMKE),
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    SLHETHONG INTEGER NOT NULL,
    SLTHUCTE INTEGER NOT NULL,
    SLLECH INTEGER NOT NULL,
    LYDOLECH TEXT
);

-- LUỒNG 4: BÁN HÀNG POS & DỊCH VỤ
CREATE TABLE HOA_DON_BAN_HANG (
    MAHOADON SERIAL PRIMARY KEY,
    MADOITAC INTEGER REFERENCES KHACH_HANG(MADOITAC),
    NGAYBAN DATE NOT NULL DEFAULT CURRENT_DATE,
    TONGTIEN BIGINT NOT NULL,
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CHI_TIET_HOA_DON (
    MACHITIET SERIAL PRIMARY KEY,
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    MAHOADON INTEGER REFERENCES HOA_DON_BAN_HANG(MAHOADON),
    SOLUONG INTEGER NOT NULL,
    DONGIA BIGINT NOT NULL,
    THANHTIEN BIGINT NOT NULL
);

CREATE TABLE DON_HANG (
    MADONHANG SERIAL PRIMARY KEY,
    MADOITAC INTEGER REFERENCES KHACH_HANG(MADOITAC), -- Có thể NULL nếu khách vãng lai
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    NGAYTAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TONGTIEN BIGINT NOT NULL DEFAULT 0,
    TRANGTHAI VARCHAR(50) NOT NULL DEFAULT 'Hold' 
);

CREATE TABLE CHI_TIET_DON_HANG (
    MACHITIET SERIAL PRIMARY KEY,
    MADONHANG INTEGER REFERENCES DON_HANG(MADONHANG) ON DELETE CASCADE,
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    SOLUONG INTEGER NOT NULL,
    DONGIA BIGINT NOT NULL,
    THANHTIEN BIGINT NOT NULL
);

CREATE TABLE DAT_LICH_DICH_VU (
    MADATLICH SERIAL PRIMARY KEY,
    MATHUCUNG INTEGER REFERENCES HO_SO_THU_CUNG(MATHUCUNG),
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM), -- ID Dịch vụ
    NGAYGIOHEN TIMESTAMP NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL -- ChoXacNhan, DaDen...
);

-- 1. BẢNG HỒ SƠ LƯƠNG (Chứa mức lương cố định của nhân viên)
-- Bảng này có quan hệ 1-1 với bảng NHANVIEN
CREATE TABLE HO_SO_LUONG (
    MANHANVIEN INTEGER PRIMARY KEY REFERENCES NHANVIEN(MANHANVIEN) ON DELETE CASCADE,
    MUCLUONG BIGINT NOT NULL DEFAULT 0, -- Lương cơ bản/Gross
    GIAMTRUBANTHAN BIGINT NOT NULL DEFAULT 11000000, -- Mặc định 11 triệu (Luật hiện hành)
    SONGUOIPHUTHUOC INTEGER NOT NULL DEFAULT 0,
    TIENGIAMNPT BIGINT NOT NULL DEFAULT 4400000, -- Mặc định 4.4 triệu / người
    NGAYCAPNHAP DATE NOT NULL DEFAULT CURRENT_DATE
);

-- 2. BẢNG PHIẾU LƯƠNG (Phát sinh hàng tháng khi chốt lương)
CREATE TABLE PHIEU_LUONG (
    MAPHIEU SERIAL PRIMARY KEY,
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    THANGNAM VARCHAR(7) NOT NULL, -- Format: 'MM/YYYY' (VD: '10/2023')
    LUONG BIGINT NOT NULL, -- Lương thực tế tính theo ngày công
    TONGBAOHIEMNV BIGINT NOT NULL DEFAULT 0,
    TONGTHUETNCN BIGINT NOT NULL DEFAULT 0,
    THUCLINH BIGINT NOT NULL, -- Lương Net
    TRANGTHAI VARCHAR(50) NOT NULL DEFAULT 'Chờ duyệt' -- Chờ duyệt, Đã thanh toán
);

-- 3. BẢNG CHI TIẾT BẢO HIỂM (Quan hệ 1-1 với PHIEU_LUONG)
CREATE TABLE CHI_TIET_BAO_HIEM (
    MAPHIEU INTEGER PRIMARY KEY REFERENCES PHIEU_LUONG(MAPHIEU) ON DELETE CASCADE,
    BHXH_NV BIGINT DEFAULT 0, -- % Trừ vào lương NV
    BHYT_NV BIGINT DEFAULT 0,
    BHTN_NV BIGINT DEFAULT 0,
    BHXH_DN BIGINT DEFAULT 0, -- % Doanh nghiệp đóng thêm
    BHYT_DN BIGINT DEFAULT 0,
    BHTN_DN BIGINT DEFAULT 0
);

-- 4. BẢNG CHI TIET THUE TNCN (1 Phiếu lương có thể có nhiều bậc thuế)
CREATE TABLE CHI_TIET_THUE_TNCN (
    MACHITIET SERIAL PRIMARY KEY,
    MAPHIEU INTEGER REFERENCES PHIEU_LUONG(MAPHIEU) ON DELETE CASCADE,
    BACTHUE INTEGER NOT NULL,
    THUNHAPCHIUTHUE BIGINT NOT NULL,
    TIENTHUE BIGINT NOT NULL
);

-- 5. BẢNG CHẤM CÔNG
CREATE TABLE CHAM_CONG (
    MACHAMCONG SERIAL PRIMARY KEY,
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    NGAY DATE NOT NULL DEFAULT CURRENT_DATE,
    GIOVAO TIMESTAMPTZ,
    GIORA TIMESTAMPTZ,
    SOGIOLAM NUMERIC(6,2) DEFAULT 0,
    TANGCA NUMERIC(6,2) DEFAULT 0,
    GHICHU TEXT
);

-- BẢNG LƯU LỊCH SỬ CÁC LẦN CHỈNH SỬA CHẤM CÔNG (DÙNG CHO QUẢN LÝ)
CREATE TABLE CHAM_CONG_SUA_LICH_SU (
    IDSUA SERIAL PRIMARY KEY,
    MACHAMCONG INTEGER REFERENCES CHAM_CONG(MACHAMCONG),
    NGUOISUA INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    NGAYSUA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GIOVAO_CU TIMESTAMPTZ,
    GIOVAO_MOI TIMESTAMPTZ,
    GIORA_CU TIMESTAMPTZ,
    GIORA_MOI TIMESTAMPTZ,
    SOGIOLAM_CU NUMERIC(6,2),
    SOGIOLAM_MOI NUMERIC(6,2),
    TANGCA_CU NUMERIC(6,2),
    TANGCA_MOI NUMERIC(6,2),
    LYDO TEXT
);

-- 6. BẢNG ĐƠN NGHỈ PHÉP
CREATE TABLE DON_NGHI_PHEP (
    MADON SERIAL PRIMARY KEY,
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    NGAY_BATDAU DATE NOT NULL,
    NGAY_KETTHUC DATE NOT NULL,
    SODAY INTEGER NOT NULL,
    LYDO TEXT,
    TRANGTHAI VARCHAR(50) NOT NULL DEFAULT 'Chờ duyệt',
    NGUOIDUYET INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    NGAYDUYET TIMESTAMP,
    NGAYTAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. BẢNG QUẢN LÝ PHÉP (số ngày phép, còn lại)
CREATE TABLE QUAN_LY_PHEP (
    MANHANVIEN INTEGER PRIMARY KEY REFERENCES NHANVIEN(MANHANVIEN),
    TONGPHEP INTEGER NOT NULL DEFAULT 12,
    CONLAI INTEGER NOT NULL DEFAULT 12,
    NGAYCAPNHAT DATE NOT NULL DEFAULT CURRENT_DATE
);
