-- LUỒNG 3: NHÂN SỰ & PHÂN QUYỀN (Tạo trước vì không phụ thuộc bảng khác)
CREATE TABLE VAI_TRO (
    MAVAITRO SERIAL PRIMARY KEY,
    TENVAITRO VARCHAR(100) NOT NULL,
    QUYENHAN JSONB NOT NULL
);

CREATE TABLE NHANVIEN (
    MANHANVIEN SERIAL PRIMARY KEY,
    HOTEN VARCHAR(255) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL
);

CREATE TABLE TAI_KHOAN_NHAN_VIEN (
    MANHANVIEN INTEGER PRIMARY KEY REFERENCES NHANVIEN(MANHANVIEN),
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORDHASH VARCHAR(255) NOT NULL,
    NGAYTAO DATE NOT NULL DEFAULT CURRENT_DATE,
    TRANG_THAI BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE PHAN_QUYEN_NHAN_VIEN (
    MAVAITRO INTEGER REFERENCES VAI_TRO(MAVAITRO),
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    PRIMARY KEY (MAVAITRO, MANHANVIEN)
);

-- LUỒNG 2: KHÁCH HÀNG & THÚ CƯNG
CREATE TABLE DOI_TAC (
    MADOITAC SERIAL PRIMARY KEY,
    TENDOITAC VARCHAR(255) NOT NULL,
    SODIENTHOAI VARCHAR(20),
    DIACHI VARCHAR(255),
    LOAIDOITAC VARCHAR(50) -- KHACH_HANG, NHA_CUNG_CAP
);

CREATE TABLE KHACH_HANG (
    MADOITAC INTEGER PRIMARY KEY REFERENCES DOI_TAC(MADOITAC),
    DIEMTICHLUY INTEGER NOT NULL DEFAULT 0,
    LOAIKHACHHANG VARCHAR(50) NOT NULL DEFAULT 'Đồng'
);

CREATE TABLE HO_SO_THU_CUNG (
    MATHUCUNG SERIAL PRIMARY KEY,
    MADOITAC INTEGER REFERENCES KHACH_HANG(MADOITAC),
    TENTHUCUNG VARCHAR(100) NOT NULL,
    LOAITHUCUNG VARCHAR(50),
    GIOITINH BOOLEAN
);

-- LUỒNG 1: SẢN PHẨM & KHO
CREATE TABLE SAN_PHAM (
    MASANPHAM SERIAL PRIMARY KEY,
    TENSANPHAM VARCHAR(255) NOT NULL,
    LOAISANPHAM VARCHAR(50) NOT NULL, -- Hàng hóa / Dịch vụ
    DONVITINH VARCHAR(20),
    GIANIEMYET BIGINT,
    COTHEMUA BOOLEAN,
    COTHEBAN BOOLEAN,
    HINHANH TEXT
);

CREATE TABLE PHIEU_KHO (
    SOPHIEU VARCHAR(50) PRIMARY KEY,
    LOAIPHIEU VARCHAR(20) NOT NULL, -- Nhập / Xuất
    NGAYLAP DATE NOT NULL DEFAULT CURRENT_DATE,
    NGUOIPHUTRACH INTEGER REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CHI_TIET_PHIEU (
    MACHITIET SERIAL PRIMARY KEY,
    SOPHIEU VARCHAR(50) REFERENCES PHIEU_KHO(SOPHIEU),
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    SOLUONG INTEGER NOT NULL,
    DONGIA BIGINT NOT NULL
);

CREATE TABLE TON_KHO (
    MASANPHAM INTEGER PRIMARY KEY REFERENCES SAN_PHAM(MASANPHAM),
    SOLUONGTON INTEGER NOT NULL DEFAULT 0
);

-- LUỒNG 4: BÁN HÀNG POS & DỊCH VỤ
CREATE TABLE HOA_DON_BAN_HANG (
    MAHOADON SERIAL PRIMARY KEY,
    MADOITAC INTEGER REFERENCES KHACH_HANG(MADOITAC),
    NGAYBAN DATE NOT NULL DEFAULT CURRENT_DATE,
    TONGTIEN BIGINT NOT NULL,
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CHI_TIET_HOA_DON (
    MACHITIET SERIAL PRIMARY KEY,
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    MAHOADON INTEGER REFERENCES HOA_DON_BAN_HANG(MAHOADON),
    SOLUONG INTEGER NOT NULL,
    DONGIA BIGINT NOT NULL,
    THANHTIEN BIGINT NOT NULL
);

CREATE TABLE DON_HANG (
    MADONHANG SERIAL PRIMARY KEY,
    MADOITAC INTEGER REFERENCES KHACH_HANG(MADOITAC), -- Có thể NULL nếu khách vãng lai
    MANHANVIEN INTEGER REFERENCES NHANVIEN(MANHANVIEN),
    NGAYTAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TONGTIEN BIGINT NOT NULL DEFAULT 0,
    TRANGTHAI VARCHAR(50) NOT NULL DEFAULT 'Hold' 
);

CREATE TABLE CHI_TIET_DON_HANG (
    MACHITIET SERIAL PRIMARY KEY,
    MADONHANG INTEGER REFERENCES DON_HANG(MADONHANG) ON DELETE CASCADE,
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM),
    SOLUONG INTEGER NOT NULL,
    DONGIA BIGINT NOT NULL,
    THANHTIEN BIGINT NOT NULL
);

CREATE TABLE DAT_LICH_DICH_VU (
    MADATLICH SERIAL PRIMARY KEY,
    MATHUCUNG INTEGER REFERENCES HO_SO_THU_CUNG(MATHUCUNG),
    MASANPHAM INTEGER REFERENCES SAN_PHAM(MASANPHAM), -- ID Dịch vụ
    NGAYGIOHEN TIMESTAMP NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL -- ChoXacNhan, DaDen...
);
